# Generated by Django 2.2.12 on 2021-01-29 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuteur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catquestion',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='domaine',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='nom',
            new_name='name',
        ),
    ]
