# Generated by Django 2.2.12 on 2021-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuteur', '0003_session_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='session_cours',
            name='pourcentage_erreur_section1',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='session_cours',
            name='pourcentage_erreur_section2',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='session_cours',
            name='pourcentage_erreur_section3',
            field=models.IntegerField(default=34),
        ),
    ]
