# Generated by Django 3.1.6 on 2021-02-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tuteur', '0005_auto_20210201_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau_social',
        ),
    ]
