# Generated by Django 3.1.6 on 2021-02-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuteur', '0006_remove_etudiant_niveau_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='libellé',
            field=models.CharField(max_length=250),
        ),
    ]
